### PR TITLE
Fix no_update caching issue (#1014)

### LINKED ISSUE #1014: [BUG] PlotlyJSONEncoder cannot serialize dash.dash._NoUpdate responses; throws TypeError
Environment:

```
dash                      1.6.1    
dash-bootstrap-components 0.7.2    
dash-core-components      1.5.1    
dash-daq                  0.3.0    
dash-flexbox-grid         0.2.1    
dash-html-components      1.0.2    
dash-renderer             1.2.1    
dash-table                4.5.1   
```

Not sure if it's related to the issue I was trying to diagnose, but I noticed the following error printed repeatedly to my console while investigating why my application spends longer (~8x longer) awaiting 204 (No Content) responses than 200 (OK) ones:

```
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/dash/dash.py", line 1328, in add_context
    response, cls=plotly.utils.PlotlyJSONEncoder
  File "/home/kz/.local/pyenv/versions/3.7.3/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/_plotly_utils/utils.py", line 44, in encode
    encoded_o = super(PlotlyJSONEncoder, self).encode(o)
  File "/home/kz/.local/pyenv/versions/3.7.3/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/kz/.local/pyenv/versions/3.7.3/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/_plotly_utils/utils.py", line 113, in default
    return _json.JSONEncoder.default(self, obj)
  File "/home/kz/.local/pyenv/versions/3.7.3/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _NoUpdate is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/dash/dash.py", line 1404, in dispatch
    response.set_data(self.callback_map[output]["callback"](*args))
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/dash/dash.py", line 1331, in add_context
    self._validate_callback_output(output_value, output)
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/dash/dash.py", line 1187, in _validate_callback_output
    _validate_value(output_value)
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/dash/dash.py", line 1180, in _validate_value
    toplevel=True,
  File "/home/kz/Envs/dash_bleedingedge/lib/python3.7/site-packages/dash/dash.py", line 1125, in _raise_invalid
    bad_val=bad_val,
dash.exceptions.InvalidCallbackReturnValue: 
The callback for `<Output `approot.children`>`
returned a value having type `_NoUpdate`
which is not JSON serializable.

The value in question is either the only value returned,
or is in the top level of the returned list,
and has string representation
`<dash.dash._NoUpdate object at 0x7ff2ca37ccf8>`

In general, Dash properties can only be
dash components, strings, dictionaries, numbers, None,
or lists of those.
```

Before filing this as a bug, I considered a possibility that this might be expected behavior. If a `_NoUpdate` object means the client state is already correct, it might make sense to crash and burn on the encoding, catch the TypeError, and return a 204 response header immediately.

But I'm pretty sure this is just a boring, garden-variety serialization bug, because (as I understand it) it's perfectly alright to sandwich `_NoUpdate` values between actual data in the return value of a multi-output callback. So I would expect `PlotlyJSONEncoder` to have a mechanism for serializing those objects.

### PR DESCRIPTION
**Pull request by ProbonoBonobo**
## Contributor Checklist

- [x] I have broken down my PR scope into the following TODO tasks
   -  [x] Ensure no_update singleton objects maintain identity after cache serialization (#1014) 
- [x] I have run the tests locally and they passed. (refer to testing section in [contributing](https://github.com/plotly/dash/blob/master/CONTRIBUTING.md))
- [ ] I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR

### optionals

- [ ] I have added entry in the `CHANGELOG.md`
- [ ] If this PR needs a follow-up in **dash docs**, **community thread**, I have mentioned the relevant URLS as follow
    -  [ ] this github [#PR number]() updates the dash docs
    -  [ ] here is the show and tell thread in plotly dash community 

____________________________

This closes #1014 by modifying the type signature of `dash._NoUpdate` to `enum.Enum` and pointing `dash.no_update` to an enumerated attribute of this class.  This ensures that `is` still works on cached responses, which currently lose their identity when memoized with `pickle.dumps`, and gives stronger assurance that `a is b` returns `True` when `a` and `b` are both aliases of `dash.no_update`.

Does this change fit within the scope of an existing test fixture? I wanted to add a unit test, but I didn't see a test fixture that pertained to HTTP Responses (and grepping "no_update" returned nothing). To make it easier to test this, it's probably sufficient to check that a no_response object obeys singleton mechanics after pickled to a string, e.g.:    

```
import enum
import pickle

class _NoUpdate(enum.Enum):
    no_update = enum.auto()

no_update = _NoUpdate.no_update
serialized = pickle.dumps(no_update)
deserialized = pickle.loads(serialized)

print(f"deserialized is no_update returns: {deserialized is no_update}")

```

(Note that it willl print `False` when executed in a Python REPL due to the implementation of `enum.Enum`, which binds to the module scope. When executed from a file, though, it prints `True` as expected.)

### CODE REVIEW

**Comment by ProbonoBonobo** [comment]
Hmm.  It's failing some CI tests because its definition of `enum.Enum` doesn't include the `auto` method, which apparently was introduced in Python 3.4.

**Comment by alexcjohnson** [comment]
@ProbonoBonobo thanks for bringing up the issue, and for giving the fix a shot! I decided to just go for an `isinstance` check as mentioned in https://github.com/plotly/dash/issues/1014#issuecomment-555056271 -> #1037

**Comment by ProbonoBonobo** [comment]
Probably the better solution, I agree. I wanted the `dash.dash.no_update` object to behave like a singleton if possible because I periodically pass it around in my own code -- a signal, usually, to suppress execution of server-side update handlers before ultimately returning that same object in the response. In theory the `enum` object provides that assurance, but resulted in some peculiar errors (Flask related) when I later tried running an application with it. Between the two, making a mental note to identify `no_update` objects by type rather than identity is the lesser of two evils, so I'll go with it 👍 

@alexcjohnson The contributor checklist is super useful by the way, but I'm wondering if Plotly has published a more comprehensive "How To" guide to setting up the testing environment? I had trouble running the primary test suite, even after locating and building `dash-renderer-test-components` from source (since it's not available in PyPi). No problems running the unit tests in `tests/unit/development` though.

**Comment by alexcjohnson** [comment]
> I had trouble running the primary test suite

Ah interesting - `dash-renderer-test-components` I know about, we've talked about how that should just be brought into this repo but somehow never made an issue for it -> https://github.com/plotly/dash/issues/1039

Is there anything else specific you can share about what additional steps you had to figure out to get the integration tests to run? Or, even better, would you like to make a PR to improve `CONTRIBUTING.md`? I think that's the right place for it, rather than a separate more complete guide.

**Pull request closed without merging**
