### PR TITLE
Performance improvement on (pattern-matching) callbacks 

### PR DESCRIPTION
**Pull request by Spriteware**
This PR is related to the issue I described here : https://github.com/plotly/dash/issues/3008 
If I encountered performance limitation with pattern-matching callbacks, I think this PR can be beneficial for regular callbacks as well.

## Contributor Checklist

- [ ] I have broken down my PR scope into the following TODO tasks
   -  [ ] task 1
   -  [ ] task 2
- [x] I have run the tests locally and they passed. (refer to testing section in [contributing](https://github.com/plotly/dash/blob/master/CONTRIBUTING.md))
- [ ] I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR

### CODE REVIEW

**Comment by chriddyp** [comment]
Awesome investigation @Spriteware , and an impressive first PR! Thank you for digging in here 🌟

**Comment by T4rk1n** [comment]
There seems to be a side effect on the test: https://github.com/plotly/dash/blob/ef003236f5258d9f2b6e00e4bc7aa7791241ee09/components/dash-core-components/tests/integration/graph/test_graph_varia.py#L684

The calls on lines https://github.com/plotly/dash/blob/ef003236f5258d9f2b6e00e4bc7aa7791241ee09/components/dash-core-components/tests/integration/graph/test_graph_varia.py#L716-L721
happens before the graph render.
If you add a time.sleep before the `Draw a shape`, it passes the test.

I think before this fix the `dash_dcc.wait_for_text_to_equal("#output", "0")` may have taken longer which allowed the graph to render.

**Comment by Spriteware** [comment]
Hey @T4rk1n thank you for digging into the failing dcc tests. I wasn't sure what to do, as the dash tests were passing locally. And not sure if I had the time and energy to go through this as well.

Excited if this gets merged!

@chriddyp Thank you for your supportive comment. If you need more investigations for optimizations, my DMs on plotly forum are indeed opened.

**Review by T4rk1n — APPROVED** [review]
:woman_dancing: Looks good, thank you.

**Comment by emilhe** [comment]
This is amazing @Spriteware ! This issue has annoyed me for ages. I can't wait for the next release 👯

**Pull request merged**
