### PR TITLE
Update pytest for testing extra (Fixes #1365)

### LINKED ISSUE #1365: [Feature Request] Support for Pytest 6
**Is your feature request related to a problem? Please describe.**
Currently, I use the dash-testing extra for writing tests for my apps. Big fan of how streamlined it makes the progress! However, it pegs pytest at v5.3.5 as a requirement, which means I can't take advantage of the new Pytest v6 release - can you say pyproject.toml and full type hinting!

**Describe the solution you'd like**
Support for pytest v6

**Describe alternatives you've considered**
Not supporting pytest v6. But there are some pretty powerful features added here, so (personally) I don't think this is a good decision. 

**Additional context**
I'm not sure if this would be a big undertaking or not. I'm happy to tackle it, if people are interested, though I'll probably have questions along the way!

### PR DESCRIPTION
**Pull request by rbpatt2019**
Update pytest and plugins to most recent version for testing extra.

## Contributor Checklist

- [X] I have broken down my PR scope into the following TODO tasks
   -  [X] Update pytest to 6.0.1
   -  [X] Update pytest-sugar to 0.9.4
   -  [X] Update pytest-mock to 3.2.0 for python 3 only!

### optionals

- [X] I have added entry in the `CHANGELOG.md`

### CODE REVIEW

**Comment by rbpatt2019** [comment]
@alexcjohnson Turns it out it isn't as simple as just upgrading pytest! Several tests now fail, all related to the following error message:

```python
/home/circleci/dash/venv/lib/python3.6/site-packages/pytest_sugar.py:214: PytestDeprecationWarning:

The TerminalReporter.writer attribute is deprecated, use TerminalReporter._tw instead at your own risk.
See https://docs.pytest.org/en/stable/deprecations.html#terminalreporter-writer for more information.
```

pytest 6.0.0 changed the way they handle deprecations - they always call as errors now, as the affected features will be removed in 6.1.0. Seems pytest-sugar uses one of these affected features (https://docs.pytest.org/en/stable/changelog.html#id19 under Terminal Writer). I'll play with updating pytest-sugar locally, and see how that goes. If it's an issue on their end, I'll raise one there!

**Comment by rbpatt2019** [comment]
That did it! The deprecation warning was fixed by updating pytest-sugar to 0.9.4. I also split pytest-mock into 2 requirements: 3.2.0 for python >= 3 and 2.0.0 for python == 2.7, which allows users to get the most up-to-date pytest -mock for their version.

**Comment by alexcjohnson** [comment]
Fantastic! Nice job figuring out `pytest-sugar` and `pytest-mock`. I think this does warrant a brief changelog entry since unlike a lot of dep bumps this impacts users (like yourself 😄), then we're ready to go!

**Comment by rbpatt2019** [comment]
That should do it! Let me know if there's anything else - always happy to contribute :)

**Pull request merged**
