### PR TITLE
remove .vscode directory

### LINKED ISSUE #834: Remove editor configuration from repo
Hi,

I previously noticed that there is a `.vscode/` folder in the index.
We should remove it from the index as it conflicts with the `.gitignore` (and mess up my own editor!).

I could make a quick PR, but first I would rather leave it to someone who wants an easy first contribution to a project.

### PR DESCRIPTION
**Pull request by Batalex**
## Contributor Checklist

- [X] I have broken down my PR scope into the following TODO tasks
   -  [X] fix #834. Remove `.vscode/` dir from git stage. It should be properly ignored for everyone using VS Code now.

We could also use this PR to discuss the addition of a `.editorconfig` file. The [homepage ](https://editorconfig.org/) shows a nice example of an editor configuration file for both Python & JS.

### CODE REVIEW

**Comment by byronz** [comment]
I'm fine to remove the vscode settings, and like the idea of a generic `editorconfig` across different IDEs. a customized version would look like this 
```
# EditorConfig is awesome: https://EditorConfig.org

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf

# Matches multiple files with brace expansion notation
# Set default charset
[*.{js,py}]
charset = utf-8

# 4 space indentation
[*.py]
indent_style = space
indent_size = 4
insert_final_newline = true

# Tab indentation (no size specified)
[Makefile]
indent_style = tab

# Indentation override for all JS under lib directory
[lib/**.js]
indent_style = space
indent_size = 2

# Matches the exact files either package.json or .travis.yml
[{package.json,.circleci/config.yml}]
indent_style = space
indent_size = 2
```

**Comment by alexcjohnson** [comment]
Sounds good to me, and this config looks like a good starting point except that our js source uses 4-space indentation just like the py source.

**Comment by Batalex** [comment]
A shorter version would be 
```
# EditorConfig is awesome: https://EditorConfig.org

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

# Matches multiple files with brace expansion notation
# Set default charset
[*.{js,py}]
charset = utf-8
indent_style = space
indent_size = 4

# Matches the exact files either package.json or .travis.yml
[{package.json,.circleci/config.yml}]
indent_style = space
indent_size = 2
```
Is this ok?
The editors support is listed [here](https://editorconfig.org/#file-location). Pycharm users would instantly benefit from it whereas Sublime/Atom/VSCode would need to install a dedicated plugin.

**Comment by byronz** [comment]
@alexcjohnson  is this valid for js file ? 
`insert_final_newline = true`

**Comment by alexcjohnson** [comment]
Currently I have my editor set to include a trailing newline on *all* files, regardless of type. So yes, definitely valid for js

**Pull request merged**
