### PR TITLE
Introduce deselectable property for datatable

### PR DESCRIPTION
**Pull request by sebihoefle**
Proposes a solution to issue https://github.com/plotly/dash/issues/1864

## Contributor Checklist

- [ ] I have broken down my PR scope into the following TODO tasks
   -  [ ] task 1
- [x] I have run the tests locally and they passed. (refer to testing section in [contributing](https://github.com/plotly/dash/blob/master/CONTRIBUTING.md))
- [x] I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR

### optionals

- [ ] I have added entry in the `CHANGELOG.md`
- [ ] If this PR needs a follow-up in **dash docs**, **community thread**, I have mentioned the relevant URLS as follows
    -  [ ] this GitHub [#PR number]() updates the dash docs
    -  [ ] here is the show and tell thread in Plotly Dash community

### CODE REVIEW

**Comment by sebihoefle** [comment]
The following example demonstrates this PR with the target use case of highlighting a row in the data table by clicking on any cell of the row.

```import dash
import dash_table
import dash_html_components as html
import dash_core_components as dcc
from dash.dependencies import Input, Output, State
import pandas as pd


app = dash.Dash(__name__)

df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/solar.csv")
df["id"] = df.index


style_data_conditional = [
    {
        "if": {"state": "active"},
        "backgroundColor": "yellow",
        "border": "1px solid blue",
    },
    {
        "if": {"state": "selected"},
        "backgroundColor": "yellow",
        "border": "1px solid blue",
    },
]

app.layout = html.Div(
    [
        dcc.Store(id="tableclick"),
        dash_table.DataTable(
            id="table",
            columns=[{"name": i, "id": i} for i in df.columns if i != "id"],
            data=df.to_dict("records"),
            page_size=4,
            filter_action="native",
            cell_deselectable=True,
        ),
    ]
)


# takes user selected cell (active_cell) and the current state of a dcc.storage (tableclick) which stores the last saved row that was clicked
# output: updated selected_rows for the datatable, styling for the selected row and update for dcc.storage
# if no cell is selected, do nothing
# if no cell is selected, but there is a row stored as selected, highlight that row (this is a consequence from the circular dependency)
# if a cell is selected that is different from the previous cell, highlight that new row. Otherwise, deselect the row.
@app.callback(
    [
        Output("table", "style_data_conditional"),
        Output("tableclick", "data"),
        Output("table", "selected_rows"),
    ],
    [
        Input("table", "active_cell"),
    ],
    [State("tableclick", "data")],
)
def highlight_row(cell, prevrow):
    if not cell:  # empty cell on deselect (click on selected)
        return [{}], None, []
    if cell is None:
        if prevrow is None:
            return [{}], None, []
        else:
            return [{}], None, [prevrow]
    elif "row" in cell:
        if cell.get("row", "") == prevrow:
            return [{}], None, []
        else:
            return (
                [
                    {  # highlight the complete row
                        "if": {"row_index": cell.get("row", "")},
                        "backgroundColor": "rgba(146, 192, 234, 0.5)",
                    },
                    {  # added code to keep style of selected cells
                        "if": {"state": "selected"},  # 'active' | 'selected'
                        "backgroundColor": "rgba(146, 192, 234, 0.5)",
                        "border": "1px solid #ddd",
                    },
                ],
                cell.get("row", ""),
                [cell.get("row", "")],
            )


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by sebihoefle** [comment]
@aCampello , if you want to make it happen, feel free to fix update the branch with dev, fix eventual CI errors (if I recall correctly there was some visual test failing) and contribute to the changelog. So far, I didn't receive any feedback from the plotly dev team about this feature/PR.

**Comment by aCampello** [comment]
Hey guys @T4rk1n  @alexcjohnson, is there any appetite for this PR that addresses #1864? I am happy to take it forward.

**Comment by gvwilson** [comment]
hi @sebihoefle - thank you again for contributing this. We're focusing our efforts on Dash AG Grid these days, and we've let this one go stale, so I'm going to close - my apologies for having left it so long.

**Pull request closed without merging**
