### PR TITLE
data-table: fixes warning about missing key prop

### PR DESCRIPTION
**Pull request by antoinerg**
Closes https://github.com/plotly/dash-table/issues/860 and potentially https://github.com/plotly/dash/issues/1433

As pointed out in https://github.com/plotly/dash-table/pull/690#issue-565576435, in order to see the warnings on the demo page, we need to use React's dev bundles (see https://github.com/plotly/dash/commit/3eac50a0e07dbad395c5d56149126a0e941a8cb0). I also changed the version of the React bundle to match the one used in `package-lock.json`. I don't know if this should stay in the PR but @chabb made a good argument for it to stay in.

The fix itself can be found in https://github.com/plotly/dash/commit/a25cca92254c34ff82cafe38d9e591703f465cda. It adds the one missing `key` prop. After this commit, the missing key warning disappears in the demo page!

cc @alexcjohnson 

## Contributor Checklist

- [ ] I have broken down my PR scope into the following TODO tasks
   -  [ ] task 1
   -  [ ] task 2
- [x] I have run the tests locally and they passed. (refer to testing section in [contributing](https://github.com/plotly/dash/blob/master/CONTRIBUTING.md))
- [x] I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR

### optionals

- [ ] I have added entry in the `CHANGELOG.md`
- [ ] If this PR needs a follow-up in **dash docs**, **community thread**, I have mentioned the relevant URLS as follows
    -  [ ] this GitHub [#PR number]() updates the dash docs
    -  [ ] here is the show and tell thread in Plotly Dash community

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Nice! Is there a way for our tests to catch this warning so we can ensure it doesn't pop up again as we change things?

> I also changed the version of the React bundle to match the one used in package-lock.json. I don't know if this should stay in the PR but @chabb made a good argument for it to stay in.

Agreed - though at some point soon we will want to make react 17 an option you can enable for any given Dash app, at first just for our own testing purposes.

**Comment by antoinerg** [comment]
> Nice! Is there a way for our tests to catch this warning so we can ensure it doesn't pop up again as we change things?

Via a Selenium test, it would probably be possible to check console logs and assert they're empty.

**Comment by antoinerg** [comment]
> Via a Selenium test, it would probably be possible to check console logs and assert they're empty.

Actually, for this to work, we also need to use a development bundle of React in the tests. I'm not sure what's the best way to do that.

cc @alexcjohnson

**Comment by alexcjohnson** [comment]
We serve the dev version of react etc when you're in debug mode. In tests we typically disable hot reloading when we turn on debug, like:

https://github.com/plotly/dash/blob/8c193bc174166513e1e043312303336b0ae169f7/tests/integration/devtools/test_devtools_ui.py#L72-L78

**Comment by antoinerg** [comment]
> Nice! Is there a way for our tests to catch this warning so we can ensure it doesn't pop up again as we change things?

Done in https://github.com/plotly/dash/pull/1778/commits/50f8c0481a77ab5b9353c81d980d1ddabc36bd26

Here's proof that this test detects the warning: https://app.circleci.com/pipelines/github/plotly/dash/2751/workflows/f3be563b-0da9-44e2-a0e1-4f0ad7796b2b/jobs/45091

**Review by alexcjohnson — APPROVED** [review]
Love it, thanks for taking care of this! Please add a quick changelog entry, then 💃

**Pull request merged**
