### PR TITLE
Added support for URL decoding of the search parameter for pages

### PR DESCRIPTION
**Pull request by yzcheung**
Here’s a structured PR description following the format you provided:

---

## Description of this PR

This PR adds support for URL decoding of the `search` parameter in pages mode. The changes ensure that URL-encoded characters in the `search` parameter are properly decoded, improving the handling of query strings in pages mode.

## Contributor Checklist

- [x] I have broken down my PR scope into the following TODO tasks
   - [x] Implement URL decoding for the `search` parameter in pages mode
- [ ] I have run the tests locally and they passed. (refer to testing section in [contributing](https://github.com/plotly/dash/blob/master/CONTRIBUTING.md))
- [ ] I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR

### optionals

- [ ] I have added entry in the `CHANGELOG.md`
- [ ] If this PR needs a follow-up in **dash docs**, **community thread**, I have mentioned the relevant URLs as follows
   - [ ] this GitHub [#PR number]() updates the dash docs
   - [ ] here is the show and tell thread in Plotly Dash community

This structure aligns with the given format and provides clear documentation of the changes.

### CODE REVIEW

**Comment by yzcheung** [comment]
This PR aims to correctly parse query parameters after URL encoding for pages.

**Review by T4rk1n — COMMENTED** [review]
Looks good, just missing a changelog entry.

**Comment by yzcheung** [comment]
> Looks good, just missing a changelog entry.

Changelog updated

**Review by T4rk1n — APPROVED** [review]
:woman_dancing: Looks good thank you.

**Pull request merged**
