### PR TITLE
Added send keys function to dash.testing

### PR DESCRIPTION
**Pull request by TakaakiFuruse**
**Problem**
Currently, dash.testing has [clear_input](https://github.com/plotly/dash/blob/149a8e853f7c94df55cd75c1735bec97717ae746/dash/testing/browser.py#L292) function which does
1. Click input box
2. Clear text

But, there's no function to input text to an input.
Adding such function would increase usability.

**Solution**

I have added a function to `dash/dash/testing/browser.py`

I know that we can do the same thing like...

```py
    input1 = dash_duo.find_element('#input')
    input1.send_keys('hello world')
```

And my way would be...

```py
    input1 = dash_duo.find_element('#input')
    dash_duo.send_key_input(input1, 'hello world')
```

I suppose, my way would make explanation and documenting easier.

# Tests
I haven't add tests as I could not figure out how. 
1. Deleting current way and replace them my new way.
2. Add my test code somewhere.

Which would be better?

*Start with a description of this PR. Then edit the list below to the items that make sense for your PR scope, and check off the boxes as you go!*

## Contributor Checklist

- [x] I have broken down my PR scope into the following TODO tasks
   -  [x] Add code
   -  [ ] Add test
- [ ] I have run the tests locally and they passed. (refer to testing section in [contributing](https://github.com/plotly/dash/blob/master/CONTRIBUTING.md))
  - (I couldn't make tests run in locally as I got some errors, I would figure out later.)
- [ ] I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR

### optionals

- [ ] I have added entry in the `CHANGELOG.md`
- [ ] If this PR needs a follow-up in **dash docs**, **community thread**, I have mentioned the relevant URLS as follow
    -  [ ] this github [#PR number]() updates the dash docs
    -  [ ] here is the show and tell thread in plotly dash community

### CODE REVIEW

**Comment by TakaakiFuruse** [comment]
I just realized that my solution would be confusing 

Rather than this..

```
    input1 = dash_duo.find_element('#input')
    dash_duo.send_key_input(input1, 'hello world')
```

This would be conprehensible..

```
    dash_duo.send_key_input('#input', 'hello world')
```

**Comment by alexcjohnson** [comment]
Thanks for the contribution!
I like your latter suggestion. Can we shorten (and match method names) to:
```py
dash_duo.send_keys('#input', 'hello world')
```

Re: tests: just change one or two of the existing tests to use your method, that should be enough.

**Comment by TakaakiFuruse** [comment]
Sure! Let mel recode my PR.

**Comment by byronz** [comment]
@TakaakiFuruse  Thank you for taking the initiative and making a first PR about `dash.testing`.  I double checked the test changes and found it might not necessary to add this extra wrapper or shortcut in `browser.py`.  

As stated in the tutorial, the purpose of our browser API abstraction is to having some syntax sugar and making the test cases more resilient.  For example, the two `find_element` and `find_elements` set the CSS selector as default and avoid the `driver` property access everywhere.  the `clear_input` involves the `ActionChain` in selenium and is a simple migration from existing test cases.  

In the case of `send_keys`,  I feel it's clearer to directly use the *Element API* from selenium like Alex did in his first migration: get the elements and do the actions. *we have no intention to wrap the whole wheel from selenium and/or web element API*

It might be more helpful to abstract some patterns if we need to handle constantly the input with certain special `Key` in the tests. I'm pretty sure you can find a better use case in the near future.

**Comment by TakaakiFuruse** [comment]
Thanks for your review!!

**Pull request closed without merging**
