### PR TITLE
register callbacks with a method in addition to decorators

### PR DESCRIPTION
**Pull request by evandam**
I hope drive-by PRs are okay! I've started playing with Dash and love it! Just a small feature I'd love to see added in! If there's a better way to accomplish this, definitely open to alternate solutions.

Similar to how Flask's [`add_url_rule`](http://flask.pocoo.org/docs/1.0/api/#flask.Flask.add_url_rule) can be used to register external functions without using `@app.route`, it would be helpful do have a similar function with callbacks. This can currently be done with `app.callback(output, inputs)(my_callback)`, but it would be nice to have a cleaner solution that allows functions to live outside of `app.py`.

Example:
**app.py**
```python
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

import my_callbacks

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div(children=[
    dcc.Input(id='my-input', value='Dash'),
    html.Div(id='my-output'),
])

app.add_callback(
    my_callbacks.greet_user,
    Output('my-output', 'children'),
    [Input('my-input', 'value')]
)

if __name__ == '__main__':
    app.run_server(debug=True)
```

**my_callbacks.py**
```python
def greet_user(name):
    return 'Hello, {}!'.format(name)
```

Don't think I can tag @plotly/dash, but tagging @rmarren1 and @T4rk1n per the contributors guide.

---

### Pre-Merge checklist
- [x] All tests on CircleCI have passed.
- [ ] All visual regression differences have been approved.
- [ ] If changes are significant, a release candidate has been created and posted to Slack, the Plotly forums, and at the very top of the pull request.
- [ ] You have updated the `dash/version.py` file and the top of `CHANGELOG.md`. For larger additions, your `CHANGELOG.md` entry includes sample code about how the feature works. The entry should also link to the original pull request(s).
- [ ] Two people have :dancer:'d the pull request. You can be one of these people if you are a Dash core contributor.

### Post-Merge checklist
- [ ] You have tagged the release using `git tag v<version_number>` _(for the contributor merging the PR)_.
- [ ] You have pushed this tag using `git push <tag_name>` _(for the contributor merging the PR)_.
- [ ] You have deleted the branch.

### Pre-Release checklist
- [ ] Everything in the Pre-Merge checklist is completed. (Except the last two if this is a release candidate).
- [ ] `git remote show origin` shows you are in the correct repository.
- [ ] `git branch` shows that you are on the expected branch.
- [ ] `git status` shows that there are no unexpected changes.
- [ ] `dash/version.py` is at the correct version.

### Release Step
- `python setup.py sdist` to build.
- `twine upload dist/<the_version_you_just_built>` to upload to PyPi.

### Post-Release checklist
- [ ] You have closed all issues that this pull request solves, and commented the new version number users should install.
- [ ] If significant enough, you have created an issue about documenting the new feature or change and you have added it to the [Documentation] project.
- [ ] You have created a pull request in [Dash Docs] with the new release of your feature by editing that project's [`requirements.txt` file](https://github.com/plotly/dash-docs/blob/master/requirements.txt) and you have assigned `@chriddyp` to review.

### CODE REVIEW

**Comment by ned2** [comment]
Hey, thanks for the PR :)

Although I'm not quite sure which situation this helps workaround. I can create an analogous version of the code snippet you provided above where `greet_user` is defined in `mycallbacks.py` and the callback is created using a function as you mention, and everything seems to work fine.

**Comment by evandam** [comment]
Awesome, thanks @ned2!

When I started playing with Dash, I found my `app.py` getting really bloated, so I wanted to separate functions into other files. However, I still had to redefine or wrap those functions in `app.py` anyway just so I could add a decorator.

As I got more into Dash, I realized this use case might be a little smaller than I thought since I ended up caching a lot, which uses decorators anyway. Still seems like it would be nice to have though!

**Comment by alexcjohnson** [comment]
@evandam it seems to me the existing syntax - while a little funny as it's a higher-order function - is just as concise without adding a new method. Your statement:
```py
app.add_callback(
    my_callbacks.greet_user,
    Output('my-output', 'children'),
    [Input('my-input', 'value')]
)
```
is equivalent to:
```py
app.callback(
    Output('my-output', 'children'),
    [Input('my-input', 'value')]
)(my_callbacks.greet_user)
```

Whether we actually want to encourage this is another question... as you point out there are other ways to address these use cases. We've started a discussion though about other possible approaches to multi-file apps that you may be interested in: #637

**Comment by alexcjohnson** [comment]
@evandam we really appreciate the thought behind this PR, and I hope you'll continue to be engaged and contribute to the project! But for the reasons above and similar described in https://github.com/plotly/dash/pull/678#issuecomment-479619711 re: minimizing the API surface, we'd prefer not to add this feature.

**Comment by evandam** [comment]
No problem! Appreciate the response @alexcjohnson!

**Pull request closed without merging**
