### PR TITLE
Add Shields.io badges to the README.

### PR DESCRIPTION
**Pull request by jbampton**
The badges give a great quick visual overview of the Dash project.  Most of the badges are links.

Hey @plotly/dash, @rmarren1  and @T4rk1n what do you think ?

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Thanks for the PR @jbampton - I like it! @chriddyp thoughts?

For reference here's what this PR gives us:
Screen Shot 2019-04-11 at 2 50 32 PM
I hadn't seen `lgtm` before, neat service, looks useful.

- I'd vote to leave out the language count and the js/ts grade - 96.9% Python says enough.
- One other thing plotly.js has front and center (cc @etpinard who may be interested in some of these other ones too) is its npm version - looks like that's easy to adapt to PyPI [PyPI version](https://badge.fury.io/py/dash)
- Also probably worth changing the circleci badge to match the style of these new ones (which plotly.js also gives an example of https://github.com/plotly/plotly.js)

**Comment by byronz** [comment]
I think we need a more concise version, listing 10+ is a little bit too exhaustive.

:1st_place_medal:  the pypi and supported python versions badges

**Comment by chriddyp** [comment]
Yeah, I'd like a more concise version. Maybe keep:
1. CircleCI
2. License
3. pypi version
4. lgtm
5. code quality: python
6. commit activity / year

contributors & last commit is pretty clear from the github repo home page.

**Comment by jbampton** [comment]
The seven badges are now added  👍

**Comment by chriddyp** [comment]
great, let's start with this and revise down the line :)

**Comment by jbampton** [comment]
Cool, thanks @chriddyp 👍

**Pull request merged**
