### PR TITLE
Allow jupyterlab v4 in dependency constraints

### PR DESCRIPTION
**Pull request by mthiboust**
Fixes https://github.com/plotly/dash/issues/2804 and https://github.com/plotly/dash/issues/2998

The current `dash` extension for `jupyterlab` cannot be installed with `jupyerlab v4`. In practice, it means that the backend is not able to communicate with the juperlab frontend to retrieve the base URL when using the `jupyter_dash.infer_jupyter_proxy_config()` method. I made it work by simply changing the dependency constraints and it is now working.

### CODE REVIEW

**Comment by gvwilson** [comment]
@marthacryan @T4rk1n does this overlap with ongoing work in Plotly.py / Plotly.js on Jupyter support?

**Comment by T4rk1n** [comment]
@gvwilson No, this is for fixing `infer_jupyter_proxy_config` for hosted jupyter notebooks.

@mthiboust Look like there is some conflict with the new version and typescript, try updating typescript in the devDependencies.

**Comment by mthiboust** [comment]
> @mthiboust Look like there is some conflict with the new version and typescript, try updating typescript in the devDependencies.

Should be ok now

**Review by T4rk1n — APPROVED** [review]
:woman_dancing: Looks good thank you.

**Pull request merged**
